# Generated by Django 3.0.5 on 2020-04-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banner/%Y%m%d/'),
        ),
    ]
